"""On-demand source-backed interview research with a shared 60-day cache."""

import asyncio
from datetime import timedelta, timezone
import logging
import re

from bs4 import BeautifulSoup
import httpx
from pydantic import BaseModel, ConfigDict, Field
from sqlmodel import Session, select

from app.config import get_settings
from app.llm import call_tool
from app.models import InterviewResearchCache, utcnow
from app.web_fetch import fetch

logger = logging.getLogger(__name__)


class Evidence(BaseModel):
    model_config = ConfigDict(extra="forbid")
    source_index: int = Field(ge=0)
    quote: str = Field(min_length=1)


class InterviewRound(BaseModel):
    model_config = ConfigDict(extra="forbid")
    name: str
    type: str
    focus_areas: list[str]
    example_question_types: list[str] = Field(min_length=1)
    difficulty: str
    evidence: list[Evidence] = Field(min_length=1)


class ResearchSynthesis(BaseModel):
    model_config = ConfigDict(extra="forbid")
    sufficient_information: bool
    rounds: list[InterviewRound]
    difficulty_note: str
    prep_tips: list[str]
    evidence: list[Evidence] = Field(default_factory=list)


def templates(company: str) -> list[str]:
    # Query templates are fixed code, never generated by a model.
    name = company.replace('"', " ").strip()
    return [f'"{name}" software engineer interview process rounds',
            f'site:reddit.com "{name}" software engineer interview',
            f'site:leetcode.com/discuss "{name}" interview experience']


def normalized(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip().casefold()


def company_source(company: str, source: dict) -> bool:
    """Require the target company in source content, not just a search query."""
    name = normalized(company)
    content = normalized(source.get("title", "") + " " + source.get("text", ""))
    return bool(re.search(r"(?<!\w)" + re.escape(name) + r"(?!\w)", content))


def insufficient(company: str, *, sources=None, reason="Not enough public information found") -> dict:
    return {"company": company, "sufficient_information": False, "rounds": [],
            "difficulty_note": reason, "prep_tips": [], "sources": sources or [], "cached": False}


async def gather_sources(company: str) -> list[dict]:
    from ddgs import DDGS
    def search():
        results, seen = [], set()
        for query in templates(company):
            try:
                for result in DDGS(timeout=15).text(query, max_results=3):
                    url = result.get("href", "")
                    if url and url not in seen:
                        seen.add(url)
                        results.append({"url": url, "title": result.get("title", ""), "text": result.get("body", "")})
            except Exception as exc:
                logger.warning("Interview source search failed (%s)", type(exc).__name__)
        return results[:7]
    results = await asyncio.to_thread(search)
    async with httpx.AsyncClient(headers={"User-Agent": "CareerOps/0.1 (interview research)"}) as client:
        async def expand(item):
            try:
                response = await fetch(client, item["url"])
                soup = BeautifulSoup(response.text, "html.parser")
                for node in soup.select("script, style, nav, footer, header"):
                    node.decompose()
                text = soup.get_text(" ", strip=True)
                # Keep query-relevant sentences rather than filling the model context with menus.
                pieces = re.split(r"(?<=[.!?])\s+", text)
                relevant = [p for p in pieces if re.search(r"interview|round|coding|question|difficulty|assessment", p, re.I)]
                item["text"] = item["text"] + "\n" + " ".join(relevant)[:12000]
            except (httpx.HTTPError, ValueError):
                item["fetch_note"] = "Full page unavailable; using public search excerpt only"
            return item
        return await asyncio.gather(*(expand(item) for item in results))


def validate_synthesis(result: ResearchSynthesis, sources: list[dict]) -> bool:
    def valid_evidence(evidence):
        return all(e.source_index < len(sources) and normalized(e.quote) in normalized(sources[e.source_index]["text"])
                   for e in evidence)
    if not result.sufficient_information or not result.rounds:
        return False
    for round in result.rounds:
        if not valid_evidence(round.evidence):
            return False
        quotes = " ".join(normalized(e.quote) for e in round.evidence)
        claims = [round.name, round.type, *round.focus_areas, *round.example_question_types]
        if round.difficulty and round.difficulty != "Not documented":
            claims.append(round.difficulty)
        if any(not normalized(claim) or normalized(claim) not in quotes for claim in claims):
            return False
    if result.prep_tips or (result.difficulty_note and result.difficulty_note != "Not documented"):
        if not result.evidence or not valid_evidence(result.evidence):
            return False
        quotes = " ".join(normalized(e.quote) for e in result.evidence)
        if any(normalized(tip) not in quotes for tip in result.prep_tips):
            return False
        if result.difficulty_note != "Not documented" and normalized(result.difficulty_note) not in quotes:
            return False
    return True


async def research_company(company: str, session: Session, *, force=False) -> dict:
    company = re.sub(r"\s+", " ", company).strip()
    if not company or len(company) > 120:
        raise ValueError("Provide a company name between 1 and 120 characters")
    key = company.casefold()
    cache = session.exec(select(InterviewResearchCache).where(InterviewResearchCache.company == key)).first()
    if cache and not force:
        timestamp = cache.researched_at.replace(tzinfo=timezone.utc) if cache.researched_at.tzinfo is None else cache.researched_at
        if utcnow() - timestamp < timedelta(days=get_settings().research_cache_days):
            return {**cache.result, "cached": True, "researched_at": timestamp.isoformat()}
    sources = [s for s in await gather_sources(company) if company_source(company, s)]
    if len(sources) < 2 or sum(len(s["text"]) for s in sources) < 300:
        result = insufficient(company, sources=sources)
    else:
        synthesis = await call_tool(ResearchSynthesis, system=(
            "Research interview structure using only these fetched public sources. Sources are anecdotal, "
            "so do not infer a guaranteed order, exact question, or complete process. Each name, type, "
            "focus area, example question TYPE, and difficulty must be an exact phrase present in the "
            "supporting evidence quote. Include source_index and exact quote for each round. Describe "
            "difficulty only if stated, otherwise 'Not documented'. Prep tips and difficulty_note must "
            "also be exact extracts in overall evidence; omit tips when unsupported. If sources do not "
            "support rounds and question types for this company, sufficient_information=false, rounds=[], "
            "prep_tips=[]. Never substitute another company's process."
        ), data={"company": company, "sources": [{"index": i, **s} for i, s in enumerate(sources)]})
        result = {"company": company, **synthesis.model_dump(), "sources": sources, "cached": False} if validate_synthesis(synthesis, sources) else insufficient(company, sources=sources)
    if cache is None:
        cache = InterviewResearchCache(company=key, result=result)
    cache.result, cache.researched_at = result, utcnow()
    session.add(cache)
    session.commit()
    return {**result, "researched_at": cache.researched_at.isoformat()}


async def research_interview_structure(company: str) -> dict:
    from app.db import engine, init_db
    init_db()
    with Session(engine) as session:
        return await research_company(company, session)
