<script lang="ts">
  import { onMount } from 'svelte';
  import Icon from '#lib/Icon.svelte';
  import { api, message, refreshWorkspace, titleCase } from '#lib/api';
  import type { Bootstrap, Source, Personalization } from '#lib/types';
  let bootstrap:Bootstrap|null=null;let sources:Source[]=[];let personalization:Personalization|null=null;let models:{id:string;name:string}[]=[];let error='';let loading=true;let saving=false;let saved=false;let recalibrating=false;let catalogLoading=false;
  let company='';let url='';let provider='auto';let industry='';let tier='';
  onMount(async()=>{try{[bootstrap,sources,personalization]=await Promise.all([api<Bootstrap>('/bootstrap'),api<Source[]>('/sources'),api<Personalization>('/personalization')]);}catch(e){error=message(e);}finally{loading=false;}});
  async function save(){saving=true;error='';saved=false;try{sources=await api<Source[]>('/sources',{method:'PUT',body:JSON.stringify(sources)});saved=true;refreshWorkspace();}catch(e){error=message(e);}finally{saving=false;}}
  function add(){if(!company.trim()||!url.trim())return;sources=[...sources,{company:company.trim(),url:url.trim(),enabled:true,provider,industry:industry.trim()||null,company_tier:tier||null}];company='';url='';industry='';tier='';saved=false;}
  async function recalibrate(){recalibrating=true;error='';try{personalization=await api<Personalization>('/personalization/recalibrate',{method:'POST'});}catch(e){error=message(e);}finally{recalibrating=false;}}
  async function catalog(){catalogLoading=true;error='';try{models=await api<typeof models>('/free-models');}catch(e){error=message(e);}finally{catalogLoading=false;}}
  async function consent(enabled:boolean){recalibrating=true;error='';try{personalization=await api<Personalization>('/personalization/consent',{method:'PUT',body:JSON.stringify({enabled})});}catch(e){error=message(e);}finally{recalibrating=false;}}
</script>
<svelte:head><title>Settings — Career Ops</title></svelte:head>
<div class="page-heading"><div><p class="eyebrow">MAKE IT WORK FOR YOU</p><h1>Your workspace settings.</h1><p>Choose your sources and understand how your matches are made.</p></div><span class="badge blue">LOCAL WORKSPACE</span></div>
{#if error}<div class="error" role="alert" style="margin-bottom:20px">{error}</div>{/if}
{#if loading}<div class="loading-line"><span class="spinner"></span>Loading workspace settings…</div>{:else}<div class="grid-two"><div class="stack">
  <section class="panel"><div class="panel-title"><h2>Free model connection</h2><span class="badge" class:green={bootstrap?.model_configured} class:amber={!bootstrap?.model_configured}>{bootstrap?.model_configured?'Configured':'Setup needed'}</span></div><p class="muted" style="font-size:12px">Natural-language parsing, resume extraction, drafts, curation, and research use OpenRouter. This workspace accepts only free models with tool calling.</p><div class="code section-gap">OPENROUTER_API_KEY=your_key_here<br/>OPENROUTER_MODEL=a_tool_calling_model:free</div><p class="fine-print" style="margin-top:12px">Put these values in the project’s .env file and restart the backend. Your key stays on the server. Free models may have availability and rate limits; failures are shown honestly.</p>{#if bootstrap?.model}<p class="model-name">Selected model: <code>{bootstrap.model}</code></p>{/if}<div class="row section-gap"><button disabled={catalogLoading} onclick={catalog}>{#if catalogLoading}<span class="spinner"></span>{/if}Check current free tool models</button><a class="text-link" href="https://openrouter.ai/models?pricing=free" target="_blank" rel="noopener noreferrer">OpenRouter catalog <Icon name="external" size={11}/></a></div>{#if models.length}<details class="section-gap" open><summary>{models.length} free tool-calling models available</summary><div class="model-list">{#each models as model}<code>{model.id}</code>{/each}</div></details>{/if}</section>
  <section class="panel"><div class="panel-title"><h2>Company career sources</h2><span class="badge">{sources.filter(s=>s.enabled).length} enabled</span></div><p class="muted" style="font-size:11px;margin-bottom:17px">Search real technology postings from these company pages. Add companies you want to follow; the search covers these sources, not the entire internet.</p><div class="stack" style="gap:10px">{#each sources as source,index}<div class="source-card"><div class="row between"><label class="row source-toggle"><input type="checkbox" bind:checked={source.enabled} onchange={()=>saved=false}/><strong>{source.company}</strong></label><button class="icon-button danger" aria-label={'Remove '+source.company+' source'} onclick={()=>{sources=sources.filter((_,i)=>i!==index);saved=false;}}><Icon name="close" size={13}/></button></div><a href={source.url} target="_blank" rel="noopener noreferrer">{source.url}</a><div class="row"><span class="badge">{source.provider}</span>{#if source.industry}<span class="badge">{source.industry}</span>{/if}{#if source.company_tier}<span class="badge">{source.company_tier} tier · user supplied</span>{/if}</div></div>{/each}</div>
    <details class="section-gap"><summary>Add a company career page</summary><form class="add-source" onsubmit={(e)=>{e.preventDefault();add();}}><div class="form-row"><label class="field">Company name<input class="input" bind:value={company} required placeholder="Company"/></label><label class="field">Provider<select class="input" bind:value={provider}><option value="auto">Detect automatically</option><option value="greenhouse">Greenhouse</option><option value="lever">Lever</option><option value="workday">Workday</option><option value="static">Static / other</option></select></label></div><label class="field">Public career page URL<input class="input" type="url" bind:value={url} required placeholder="https://job-boards.greenhouse.io/company"/></label><div class="form-row"><label class="field">Industry, if you know it<input class="input" bind:value={industry} placeholder="Optional, e.g. fintech"/></label><label class="field">Company tier, if you know it<select class="input" bind:value={tier}><option value="">Unknown — don't infer</option><option value="low">Low</option><option value="mid">Mid</option><option value="high">High</option></select></label></div><p class="fine-print">Industry and company tier are used only when you provide them or the posting explicitly states them.</p><button type="submit"><Icon name="plus" size={13}/>Add source</button></form></details><div class="row section-gap"><button class="primary" disabled={saving} onclick={save}>{saving?'Saving…':'Save source changes'}</button>{#if saved}<span class="saved-message" role="status"><Icon name="check" size={13}/>Sources saved</span>{/if}</div>
  </section>
</div><div class="stack"><section class="panel"><div class="panel-title"><h2>Your ranking, over time</h2><span class="badge" class:green={personalization?.active}>{personalization?.active?'Personalized':'Layer 1'}</span></div><p class="fine-print">Learn scoring weights locally from your logged outcomes only after you opt in. Turning this off deletes the learned weights.</p><button class="section-gap" disabled={recalibrating} onclick={()=>consent(!personalization?.enabled)}>{personalization?.enabled?'Turn off local learning':'Enable local learning'}</button><div class="calibration-count"><strong>{personalization?.outcome_count || 0}</strong><span>logged outcomes<br/>of {personalization?.minimum_outcomes || 6} needed to begin</span></div><div class="progress-track"><span style={'width:'+Math.min(100,((personalization?.outcome_count || 0)/(personalization?.minimum_outcomes || 6))*100)+'%'}></span></div><p class="muted" style="font-size:11px;margin-top:17px">{personalization?.reason}</p><p class="fine-print" style="margin-top:13px">Interview and offer are positive outcomes. Rejection and no response are negative evidence. Each application counts once; withdrawals do not train the scorer.</p><button class="section-gap" disabled={recalibrating || !personalization?.enabled} onclick={recalibrate}>{recalibrating?'Recalibrating…':'Recalibrate now'}</button>{#if personalization?.active}<details class="section-gap"><summary>View learned adjustments</summary>{#each Object.entries(personalization.weights) as [name,weight]}<div class="weight"><span>{titleCase(name)}</span><code>{weight>0?'+':''}{weight.toFixed(4)}</code></div>{/each}</details>{/if}</section><section class="panel privacy"><Icon name="info" size={21}/><h2>Clear boundaries.</h2><p>Fit scores show content match, not a hiring probability. Hard filters stay strict; soft preferences affect the score.</p><p>Resume embeddings run locally. Generative calls request providers that disallow training data collection. Your application status changes only when you act.</p><p>This is a local single-user workspace. Accounts and public deployment belong to later phases.</p></section></div></div>{/if}
<style>
  .source-card{border:1px solid var(--line);border-radius:8px;padding:13px}.source-toggle{font-size:12px;gap:8px}.source-toggle input{accent-color:var(--blue)}.source-card>a{display:block;font-size:10px;color:#95a5bf;margin:9px 0 11px;overflow-wrap:anywhere}.source-card .badge{font-size:9px}.model-name{font-size:10px;color:#8d9cb1;margin-top:13px;overflow-wrap:anywhere}.model-list{display:grid;gap:9px;font-size:10px;max-height:250px;overflow:auto;margin-top:15px;padding:10px;background:#f7f9fd;border-radius:7px;color:#778dab}.add-source{display:grid;gap:15px;margin-top:18px}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:13px}.add-source .input{font-size:11px}.add-source button{justify-self:start;font-size:11px}.saved-message{display:flex;align-items:center;gap:5px;color:#448669;font-size:11px}.calibration-count{display:flex;align-items:center;gap:13px;margin:24px 0 19px}.calibration-count strong{font-family:Manrope,sans-serif;font-size:39px;color:#6989c0;letter-spacing:-2px}.calibration-count span{font-size:10px;color:#9aabc3;line-height:1.8}.progress-track{height:5px;background:#edf1f8;border-radius:5px;overflow:hidden}.progress-track span{height:100%;display:block;background:#91b1e9;border-radius:5px}.privacy{background:#f4f7fc;border-color:#e9eef5;padding:27px}.privacy>:global(svg){color:#93a8c9;margin-bottom:19px}.privacy h2{font-size:18px;margin-bottom:16px}.privacy p{font-size:11px;color:#93a2ba;line-height:1.9;margin-top:15px}.weight{display:flex;justify-content:space-between;font-size:10px;color:#8a9bb6;padding:8px 0;border-bottom:1px solid var(--line)}@media(max-width:700px){.form-row{grid-template-columns:1fr}.page-heading>.badge{display:none}.panel .row.section-gap{flex-wrap:wrap}}
</style>
