<script lang="ts">
  import { onMount } from 'svelte';
  import Icon from '#lib/Icon.svelte';
  import { api, message, refreshWorkspace, titleCase } from '#lib/api';
  import type { Bootstrap, Profile } from '#lib/types';
  let profile: Profile | null=null; let bootstrap: Bootstrap | null=null; let loading=true; let uploading=false; let error=''; let drag=false;
  let memory: {fact_text:string;fact_type:string;source:string}[]=[];
  async function load(){try{[profile,bootstrap,memory]=await Promise.all([api<Profile|null>('/resume'),api<Bootstrap>('/bootstrap'),api<typeof memory>('/memory')]);}catch(e){error=message(e);}finally{loading=false;}}
  onMount(load);
  async function upload(file:File|undefined){if(!file)return;uploading=true;error='';try{const body=new FormData();body.append('file',file);await api('/resume',{method:'POST',body});await load();refreshWorkspace();}catch(e){error=message(e);}finally{uploading=false;}}
  async function remove(){error='';try{await api('/resume',{method:'DELETE'});await load();refreshWorkspace();}catch(e){error=message(e);}}
</script>
<svelte:head><title>Resume & facts — Career Ops</title></svelte:head>
<div class="page-heading"><div><p class="eyebrow">YOUR EXPERIENCE, AS IT IS</p><h1>A grounded starting point.</h1><p>Your resume becomes the source of truth for every match and every draft.</p></div>{#if profile}<span class="badge green"><Icon name="check" size={12}/>{profile.structured_facts.facts.length} sourced facts</span>{/if}</div>
{#if error}<div class="error" role="alert" style="margin-bottom:20px">{error}</div>{/if}
{#if loading}<div class="loading-line"><span class="spinner"></span>Loading your resume…</div>{:else}<div class="grid-two"><div class="stack">
  <section class="panel"><div class="panel-title"><h2>{profile?'Your current resume':'Add your resume'}</h2><span class="badge">OPTIONAL</span></div>
    {#if profile}<div class="current-file"><span class="file-icon"><Icon name="file" size={24}/></span><div><strong>{profile.filename}</strong><small>Updated {new Date(profile.updated_at).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</small></div><button class="subtle-button danger" onclick={remove} disabled={uploading}>Remove</button></div><div class="notice" style="margin:17px 0"><Icon name="info" size={15}/><span>{profile.latex_source?'Your .tex source is stored. Curation preserves formatting outside edited statements.':'PDF/Word curation uses a new clean layout. To preserve your original layout, upload the .tex source.'}</span></div>{/if}
    {#if profile?.layout_advisory}<div class="notice" style="margin-bottom:16px"><Icon name="info" size={15}/><span>{profile.layout_advisory}</span></div>{/if}
    <label class="upload-zone" class:drag class:disabled={!bootstrap?.model_configured || uploading} ondragover={(e)=>{e.preventDefault();drag=true;}} ondragleave={()=>drag=false} ondrop={(e)=>{e.preventDefault();drag=false;if(bootstrap?.model_configured&&!uploading)upload(e.dataTransfer?.files[0]);}}>
      <input type="file" accept=".tex,.pdf,.docx,.txt" aria-label="Upload resume" disabled={!bootstrap?.model_configured || uploading} onchange={(e)=>upload(e.currentTarget.files?.[0])}/><span class="empty-icon"><Icon name="upload" size={23}/></span><strong>{uploading?'Reading and checking your resume…':profile?'Replace your resume':'Drop your resume here'}</strong><p>{uploading?'Extracting exact source facts using your free model.':'or click to browse your files'}</p><small>.tex · PDF · Word (.docx) · Text · Up to 5 MB</small>
    </label>
    {#if !bootstrap?.model_configured}<p class="fine-print" style="margin-top:13px">Resume fact extraction requires a <a href="/settings">configured free model</a>. You can search jobs without uploading a resume.</p>{/if}
    {#if uploading}<div class="loading-line" role="status" style="margin-top:15px"><span class="spinner"></span>Keeping only facts traceable to your uploaded text…</div>{/if}
  </section>
  {#if profile}<section class="panel"><div class="panel-title"><h2>What your resume says</h2><span class="badge">{profile.structured_facts.facts.length} facts</span></div><p class="muted" style="font-size:11px;margin-bottom:18px">Every statement below is an exact extract from your resume. No inferred employers, metrics, or skills.</p><div class="stack" style="gap:10px">{#each profile.structured_facts.facts as fact}<div class="fact"><span class="badge blue">{titleCase(fact.category)}</span><p>{fact.text}</p><small>{fact.id}</small></div>{/each}</div><details class="section-gap"><summary>View extracted source text</summary><pre class="source-text">{profile.raw_resume_text}</pre></details></section>{/if}
</div><div class="stack"><section class="panel guidance"><span class="guidance-icon"><Icon name="sparkle" size={19}/></span><h2>Your experience stays yours.</h2><p>Tailoring selects relevant stored facts for one job at a time. A separate critic checks claims before they reach your application materials.</p><div class="divider"></div><h3>For precise curation</h3><p>Upload an Overleaf or LaTeX <strong>.tex source</strong>. Only selected statements change; the surrounding layout stays intact.</p><h3 style="margin-top:20px">For PDF or Word</h3><p>We can use your facts in a clean template. The result is clearly labeled as a new layout.</p></section><section class="panel"><div class="panel-title"><h2>Workspace memory</h2><span class="badge">{memory.length}</span></div><p class="muted" style="font-size:11px">Current resume facts and outcomes you log. Replacements and corrections update existing records.</p>{#if memory.filter(f=>f.source==='outcome').length}<div class="stack section-gap" style="gap:10px">{#each memory.filter(f=>f.source==='outcome') as fact}<div class="fact"><span class="badge">Logged outcome</span><p>{fact.fact_text}</p></div>{/each}</div>{:else}<p class="fine-print" style="margin-top:18px">No application outcomes logged yet. Your feedback will appear here as your search progresses.</p>{/if}</section></div></div>{/if}
<style>
  .upload-zone{display:flex;align-items:center;justify-content:center;flex-direction:column;text-align:center;border:1px dashed #cbd8ed;border-radius:10px;background:#f9fbff;padding:32px 15px;cursor:pointer;position:relative}.upload-zone:hover,.upload-zone.drag{border-color:var(--blue);background:#f2f6ff}.upload-zone.disabled{opacity:.65;cursor:not-allowed}.upload-zone input{position:absolute;inset:0;width:100%;height:100%;opacity:0;cursor:inherit}.upload-zone .empty-icon{width:45px;height:45px;border-radius:12px;margin:0 0 15px}.upload-zone strong{font-size:12px;color:#6e83a6}.upload-zone p{font-size:11px;color:#a1aec2;margin-top:6px}.upload-zone small{font-size:9px;color:#aeb9ca;margin-top:19px}.current-file{border:1px solid var(--line);padding:15px;border-radius:8px;display:flex;align-items:center;gap:13px}.file-icon{background:#f1f5ff;color:#789acb;width:40px;height:44px;border-radius:7px;display:grid;place-items:center}.current-file strong{font-size:12px;word-break:break-all}.current-file small{display:block;color:#99a6b8;font-size:10px;margin-top:6px}.current-file button{margin-left:auto;font-size:10px}.guidance{background:#f2f6ff;border-color:#e5ecfa;padding:26px}.guidance-icon{color:#7797ce;background:white;width:37px;height:37px;display:grid;place-items:center;border-radius:10px;margin-bottom:20px}.guidance h2{font-size:18px;line-height:1.5;margin-bottom:14px}.guidance p{font-size:12px;color:#8497b4;line-height:1.9}.guidance h3{font-size:12px;margin-bottom:10px;color:#627b9f}.source-text{font-size:11px;line-height:1.8;white-space:pre-wrap;color:#94a0b1;max-height:350px;overflow:auto}
</style>
